export const trainingTeam = {
  department: '教育訓練交付部',
  focus: '課程交付',
  note: '五個 Agent 加兩個人工控制點，Chain 一條龍。AI 產出全部是草稿，講師定稿才算數。教材掛的是講師的專業信譽，這是不能外包的底線。',
  scopeNote:
    '涵蓋企業內訓與線上課程的教材產出流程。編號 T01–T05 為此規格內部編號，與組織圖的 T 系列一致。',
  flow: [
    { step: '確認課程目標', owner: '留人', reason: '判斷客戶真正要解決的問題' },
    {
      step: '設計課綱',
      owner: 'Agent：課綱設計員（Worker）',
      reason: '依對象與時數草擬單元與教學順序',
    },
    {
      step: '草擬簡報',
      owner: 'Agent：簡報草擬員（Worker）',
      reason: '把課綱展開成逐頁內容與講述提示',
    },
    {
      step: '編寫講義與範例',
      owner: 'Agent：講義與範例編寫員（Worker）',
      reason: '產出學員拿得走的講義、練習與範例檔',
    },
    {
      step: '撰寫講師講稿',
      owner: 'Agent：講師講稿撰寫員（Worker）',
      reason: '把簡報轉成可照著講的逐段講稿',
    },
    { step: '講師審核', owner: '留人', reason: '專業正確性與教學邏輯把關' },
    { step: '正式授課', owner: '留人', reason: '現場判斷、提問回應與臨場調整' },
    {
      step: '整理課後回饋',
      owner: 'Agent：課後回饋整理員（Worker）',
      reason: '把問卷與提問收斂成教材改善建議',
    },
  ],
  agents: [
    {
      id: 'T01',
      name: '課綱設計員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '根據課程目標、對象與時間，草擬課程單元及教學順序。',
      step: '設計課綱',
      inputLabel: '建議輸入',
      inputs: [
        '客戶產業與實際痛點',
        '學習對象、人數與程度',
        '可用時數與場地限制',
        '客戶指定主題或政府計畫要求',
        '過往同類課程的回饋',
      ],
      outputLabel: '建議輸出',
      output: [
        '【課程目標】',
        '【學習對象】',
        '【單元架構】',
        '【各單元時間】',
        '【教學活動】',
        '【學習成果】',
        '【需講師確認】',
      ],
      limits: [
        '承諾學習成果',
        '決定授課日期',
        '決定收費',
        '把未確認的需求寫成已確認',
      ],
      rule: '課綱是草稿。講師定稿後才進入簡報製作，避免整包重做。',
    },
    {
      id: 'T02',
      name: '簡報草擬員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '根據核准課綱，草擬課程簡報的頁面架構與內容。',
      step: '草擬簡報',
      inputLabel: '建議輸入',
      inputs: ['已核准課綱', '品牌簡報模板', '可引用的案例與數據來源清單'],
      outputLabel: '建議輸出',
      output: [
        '【投影片頁次】',
        '【每頁標題】',
        '【每頁重點】',
        '【講述提示】',
        '【圖表建議】',
        '【需查證項目】',
      ],
      limits: [
        '引用未查證的數據、案例或法規',
        '杜撰企業案例',
        '使用未授權圖片',
        '把示範資料寫成真實資料',
      ],
      rule: '需查證項目必須明確標出，不得以推測把版面填滿。',
    },
    {
      id: 'T03',
      name: '講義與範例編寫員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '依據課綱與簡報內容，編寫講義、練習題及教學範例草稿。',
      step: '編寫講義與範例',
      inputLabel: '建議輸入',
      inputs: ['已核准課綱與簡報', '學員程度與先備知識', '實作環境與軟體限制'],
      outputLabel: '建議輸出',
      output: [
        '【講義大綱】',
        '【逐節說明】',
        '【練習題】',
        '【範例檔說明】',
        '【操作步驟】',
        '【常見錯誤】',
        '【需講師確認】',
      ],
      limits: [
        '虛構研究來源',
        '杜撰企業案例',
        '使用未授權教材',
        '把示範數據冒充真實資料',
      ],
      rule: '範例資料一律標示為示範用，絕不使用真實客戶資料。',
    },
    {
      id: 'T04',
      name: '講師講稿撰寫員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '將課程內容整理成講師可使用的講解重點與授課講稿。',
      step: '撰寫講師講稿',
      inputLabel: '建議輸入',
      inputs: ['定稿簡報', '課綱的時間分配', '講師慣用語氣與節奏偏好'],
      outputLabel: '建議輸出',
      output: [
        '【開場】',
        '【逐段講稿】',
        '【每段時間】',
        '【轉場語】',
        '【互動提問】',
        '【結語】',
        '【備用內容】',
      ],
      limits: [
        '代替講師做專業判斷',
        '承諾課後服務或額外支援',
        '加入未經講師確認的觀點',
      ],
      rule: '講稿只是輔助。現場判斷與提問回應由講師負責，講稿須經講師改寫後才使用。',
    },
    {
      id: 'T05',
      name: '課後回饋整理員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '彙整學員問卷、意見與課堂紀錄，形成課程改善摘要。',
      step: '整理課後回饋',
      inputLabel: '建議輸入',
      inputs: ['學員問卷', '課堂提問紀錄', '講師觀察', '客戶單位的回饋'],
      outputLabel: '建議輸出',
      output: [
        '【整體滿意度】',
        '【學員肯定事項】',
        '【常見問題】',
        '【需要改善事項】',
        '【建議調整方向】',
        '【資料限制】',
      ],
      limits: [
        '直接修改正式教材',
        '對學員承諾補課或退費',
        '隱藏成效不佳或負面的回饋',
      ],
      rule: '回饋只產生改善建議。教材要不要改、怎麼改，由講師決定。',
    },
  ],
  gates: [
    {
      id: 'H01',
      name: '講師審核（留人）',
      checkLabel: '講師應確認',
      checks: [
        { item: '專業正確性', detail: '內容、數據、法規與案例是否正確' },
        { item: '教學邏輯', detail: '單元順序與難度是否適合這批學員' },
        { item: '資料來源', detail: '引用是否可查證、是否已標示需查證項目' },
        { item: '客戶機密與個資', detail: '範例是否誤用真實客戶資料' },
        { item: '時間可行性', detail: '實際講得完嗎、有無留互動時間' },
        { item: '教材授權', detail: '圖片、模板與引用是否合法可用' },
      ],
      decisionLabel: '審核結果',
      decisions: [
        '核准 → 進入下一步或準備授課',
        '退回修改 → 附上意見回到該 Agent',
        '資料不足 → 補齊查證項目後重做',
        '方向不符 → 回到課綱重新設計',
      ],
      rule: '教材掛的是講師的專業信譽，AI 產出一律視為草稿。不另設 Reviewer Agent。',
    },
    {
      id: 'H02',
      name: '正式授課（留人）',
      checkLabel: '只有人能做的事',
      checks: [
        { item: '現場調整', detail: '依學員反應改變節奏與深度' },
        { item: '提問回應', detail: '回答課綱之外的實務問題' },
        { item: '敏感議題處理', detail: '涉及客戶內部人事或爭議時的分寸' },
        { item: '個資與機密', detail: '學員自曝的公司資訊如何處理' },
        { item: '課後承諾', detail: '是否答應補充資料、後續諮詢或額外服務' },
      ],
      rule: '授課是人的責任，AI 不參與現場，也不得代為對學員作出任何承諾。',
    },
  ],
  permissionChain:
    'AI 設計課綱 → AI 草擬簡報 → AI 編寫講義與範例 → AI 撰寫講稿 → 講師審核 → 講師授課 → AI 整理回饋 → 講師決定教材怎麼改',
  permissions: [
    { action: '讀取已核准教材與模板', allowed: true },
    { action: '依課綱產出簡報大綱', allowed: true },
    { action: '編寫講義與練習題', allowed: true },
    { action: '撰寫講稿初稿', allowed: true },
    { action: '整理課後回饋', allowed: true },
    { action: '標示需查證項目', allowed: true },
    { action: '決定授課日期與收費', allowed: false },
    { action: '承諾學習成果', allowed: false },
    { action: '引用未查證的數據或法規', allowed: false },
    { action: '使用未授權教材或圖片', allowed: false },
    { action: '拿真實客戶資料當範例', allowed: false },
    { action: '直接修改定稿教材', allowed: false },
    { action: '對學員承諾補課或退費', allowed: false },
  ],
  notConfigured: [
    { type: 'Router 分派員', reason: '課程製作是固定流程，沒有分流需求' },
    { type: 'Reviewer 審查員', reason: '講師本人就是專業審核者，多一層 AI 審查不能取代專業責任' },
    { type: 'Manager 管理員', reason: '五個 Agent 依序合作，不需要 AI 管理層' },
    { type: 'Executive 決策員', reason: '課程方向、定價與對客戶的承諾由人決定' },
  ],
}
