export const opsTeam = {
  department: '營運與財務管理部',
  note: '四個 Agent 加三個人工控制點，形成一條固定的 Chain 流程，不需要 Branch 或 Parallel。AI 成為每日營運幕僚，但不成為公司的管理者。',
  scopeNote:
    '本區為每日營運資訊整理流程的實作規格，內容已依顧問業調整（案件、應收付款、專案排程）。編號 A01–A04 為此規格內部編號。合約、請款與核銷的 Agent 配置尚未定義。',
  flow: [
    {
      step: '彙整今日營運資訊',
      owner: 'Agent：營運資訊整理員（Worker）',
      reason: '把分散的案件、帳務與行程資料整理到能看',
    },
    {
      step: '整理待辦事項',
      owner: 'Agent：待辦整理員（Worker）',
      reason: '依既有規則提出優先順序建議',
    },
    {
      step: '檢查異常狀況',
      owner: 'Agent：營運監測員（Knowledge）',
      reason: '依既有營運規則標示可能異常',
    },
    {
      step: '產出每日營運摘要',
      owner: 'Agent：營運摘要員（Worker）',
      reason: '整理成供負責人閱讀的摘要',
    },
    { step: '負責人檢視', owner: '留人', reason: '確認資料與實際營運狀況' },
    { step: '決定今日工作安排', owner: '留人', reason: '決定優先順序、人力與資源配置' },
    { step: '通知各部門', owner: '留人', reason: '正式發布工作指示' },
  ],
  agents: [
    {
      id: 'A01',
      name: '營運資訊整理員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '彙整今日案件、應收付款、專案進度與行程等營運資訊。',
      step: '彙整今日營運資訊',
      inputLabel: '建議輸入',
      inputs: [
        '今日案件與工單資料',
        '應收付款紀錄',
        '專案排程',
        '會議與工作行程',
        '各部門回報資訊',
      ],
      outputLabel: '建議輸出',
      output: [
        '【今日案件】',
        '【應收付款】',
        '【專案進度】',
        '【重要行程】',
        '【缺少資料】',
      ],
      limits: [
        '修改案件資料',
        '調整帳務數字',
        '更改專案排程',
        '自行判斷工作優先順序',
        '對各部門發布指示',
      ],
    },
    {
      id: 'A02',
      name: '待辦整理員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '整理今日待辦事項並依優先順序列出工作清單。',
      step: '整理待辦事項',
      outputLabel: '建議輸出',
      output: [
        '【高優先待辦】',
        '【一般待辦】',
        '【可延後事項】',
        '【負責人待確認】',
        '【期限待確認】',
      ],
      limits: [
        '正式決定優先順序',
        '指定或更換負責人',
        '承諾完成時間',
        '延後已確認的任務',
        '取消工作項目',
      ],
      rule: '「依優先順序列出」只是 AI 建議，最終順序仍由負責人決定。',
    },
    {
      id: 'A03',
      name: '營運監測員',
      type: 'Knowledge 知識員',
      assignee: '待指派',
      duty: '依據既有營運規則找出可能需要注意的異常狀況。',
      step: '檢查異常狀況',
      scopeLabel: '可檢查的異常類型',
      scope: [
        '案件即將逾期',
        '應收款逾期',
        '專案排程衝突',
        '工作期限即將到期',
        '行程或人力安排重疊',
        '資料缺漏或數字不一致',
      ],
      outputLabel: '建議輸出',
      output: [
        '【異常項目】',
        '【觸發規則】',
        '【相關資料】',
        '【可能影響】',
        '【建議由人確認事項】',
      ],
      limits: ['自行制定異常標準', '判定問題責任', '調整排程', '調度人員', '發布緊急指示'],
      rule: '若沒有明確規則，標示「需人判斷」，不可自行推測。',
    },
    {
      id: 'A04',
      name: '營運摘要員',
      type: 'Worker 執行員',
      assignee: '待指派',
      duty: '整理每日重點資訊並產出供負責人閱讀的營運摘要。',
      step: '產出每日營運摘要',
      outputLabel: '建議輸出格式',
      output: [
        '【今日營運概況】',
        '【重要待辦】',
        '【異常提醒】',
        '【今日重要期限】',
        '【需要負責人決定】',
        '【資料不足事項】',
      ],
      limits: [
        '決定今日工作安排',
        '直接要求部門執行',
        '更改人員分工',
        '核准臨時支出',
        '對外承諾交期',
        '隱藏或刪除不利資訊',
      ],
    },
  ],
  gates: [
    {
      id: 'H01',
      name: '負責人檢視（留人）',
      checkLabel: '負責人需要確認',
      checks: [
        { item: '資料正確性', detail: '案件、帳務、專案與行程是否正確' },
        { item: '現場狀況', detail: 'AI 摘要是否符合實際營運' },
        { item: '異常重要性', detail: '是否真的需要立即處理' },
        { item: '資訊完整性', detail: '是否有部門尚未回報' },
        { item: '決策限制', detail: '是否涉及成本、人員或對外承諾' },
      ],
      rule: '需要綜合考量人力、案件、帳務、活動與突發事件，確認 AI 提供的資訊是否符合實際情況。',
    },
    {
      id: 'H02',
      name: '決定今日工作安排（留人）',
      checkLabel: '這一步包含管理責任',
      checks: [
        { item: '今日最優先工作', detail: '決定先做什麼' },
        { item: '人員安排與任務調度', detail: '誰做、什麼時候做' },
        { item: '資源分配', detail: '時間與預算怎麼投' },
        { item: '臨時插單處理', detail: '插進來的要不要接' },
        { item: '延後或取消事項', detail: '什麼可以先放著' },
        { item: '緊急狀況因應', detail: '突發事件怎麼處理' },
      ],
      rule: 'AI 可以提出建議，但不能直接成為正式工作指令。',
    },
    {
      id: 'H03',
      name: '通知各部門（留人）',
      checkLabel: 'Agent 不應直接做的事',
      checks: [
        { item: '指派員工', detail: '正式指派工作代表公司的管理指令' },
        { item: '更改排班', detail: '人力調度屬於管理決策' },
        { item: '發布強制要求', detail: '對內指令須由人具名' },
        { item: '承諾完成期限', detail: '期限責任必須有人承擔' },
        { item: '通知客戶交期變動', detail: '對外表態須經核准' },
        { item: '對外發布營運決定', detail: '代表公司的決定不可自動發出' },
      ],
      rule: '正式通知代表公司管理指示，應由負責人或授權主管執行。',
    },
  ],
  permissionChain: 'AI 可讀取 → AI 可整理 → AI 可標示異常 → AI 可產出摘要 → AI 不可決定 → AI 不可指派 → AI 不可通知各部門',
  permissions: [
    { action: '讀取案件與帳務資料', allowed: true },
    { action: '整理營運資訊', allowed: true },
    { action: '提出優先順序建議', allowed: true },
    { action: '標示規則型異常', allowed: true },
    { action: '產出營運摘要', allowed: true },
    { action: '更改案件或帳務資料', allowed: false },
    { action: '調整人力或排班', allowed: false },
    { action: '正式指派工作', allowed: false },
    { action: '通知各部門執行', allowed: false },
    { action: '對客戶承諾交期', allowed: false },
  ],
  notConfigured: [
    { type: 'Router 分派員', reason: '每日營運流程固定，不需案件分流' },
    { type: 'Reviewer 審查員', reason: '每日摘要直接由負責人檢視' },
    { type: 'Manager 管理員', reason: 'AI 不應管理或指揮公司員工' },
    { type: 'Executive 決策員', reason: '人力調度、資源配置與營運決策由人負責' },
  ],
}
